name: Basic Work Flow Example
on:
 workflow_dispatch:
 
jobs:
  build:
   name: Testing Work Flow
   runs-on: macos-latest
   steps: 
     - run: |
            echo "Sample  Work flow Test"
            VERSIONNUMBERPREFIX = $(date + "%y.%m.%d")
            echo "Version no is $VERSIONNUMBERPREFIX"
            BUILDNUMBERPREFIX = $(date + "%y%m%d")
            echo "Build no is $BUILDNUMBERPREFIX"
