name: Basic Work Flow Example
on:
 workflow_dispatch:
 
jobs:
  build:
   name: Testing Work Flow
   runs-on: macos-latest
   steps: 
     - name: First Work Flow
     - run: echo "Sample Work flow Test"
            echo "Testing"
