name: Basic Work Flow Example
on:
 workflow_dispatch:
 
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true 
  
jobs:
  create-release-branch:
   runs-on: macos-latest
   steps: 
     - name: Get Current Date
       id: date
       run:  echo "date=$(date +'%y.%m.%d')"
            
